/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import lab2.ex1.Book;
import lab2.ex2.*;

public class Library {
	public static void main(String arg[]) {
		final String arr[]= {"Basic Java","Advance Java","Forget about Java"};
		Book b = new Book(arr);
		System.out.println("The title of Ch. 1 is " + b.getChapter(1));
		String anotherArr[]=b.getChapters();
		
		System.out.println("There're "+anotherArr.length+" chapters.");
		System.out.println(java.util.Arrays.toString(anotherArr));
		
		Computer ALau = new MobileComputer();
		for (int i=0;i<10;i++) ALau.work();
		
		Charger c = new Charger();
		Phone p = new Phone();
		MobileComputer m = new MobileComputer();
		c.charge(p);
		c.charge(m); //this doesn't work without fixing MobileComputer
		
	}
    public boolean someLibraryMethod() {return true;}
}